- main/main.js
- package-lock.json
The title says it all.
Tested it, and it seems to work.
If you have any questions, just let me know :)
> Hide Menu Bar, Bump NPM Packaging

- main/main.js
> Hide Tilebar

- package-lock.json
- package.json
> add electron forge

- src/functions.js
- src/index.html
- src/loader.js
- src/search.js
- src/tabs.js
- styles.css
> Better Tabs

- .github/workflows/build.yml
- package-lock.json
- package.json
This is a bit different from the ninetails system.
What you first do, is create a tag that starts with v, like this from https://dev.to/erikhofer/build-and-publish-a-multi-platform-electron-app-on-github-3lnd where I got this system from:
Then, a draft PR should come up in your releases. Edit the description and stuff, then release it!
> add auto building

- .github/workflows/build.yml
- package.json
Now tailwind styles should come with the built versions.
> Fix tailwind

- src/index.html
Can you test this and tell me if it works?
> hide overflow

- src/index.html
Please test, do not merge if it isn't fixed. You can use the github CLI to check this out. If you don't have it, please get it! `gh`
> does this work?

- styles.css
If some websites break, this may fix it.
> webview style

- main/main.js
- src/tabs.js
This adds a bit of support for `window.open()` and some more event listeners on the Webview.
> Window listeners

- src/index.html
This changes the capitalisation in `index.html` to fit in with the rest of the code in `index.html`.
> Change capitalisation

- src/index.html
> Colour fix

- package-lock.json
- package.json
This was just a quick one, I was going to add a special banner, but I don't know which dimensions to use. I tried to use `banner.svg` but it was not fitting properly when I inserted the DMG.
The reason why is because it will make the install process even quicker so MacOS users can add it to their `/Applications` folder which will automatically add it to Launchpad and maybe some other tools. (also because basically every app either comes as dmg or pkg but dmg is better I think)
> Add DMG building

- src/functions.js
- src/search.js
- src/tabs.js
This adds the event listener so when you press Enter in the search bar it automatically searches. I am going to work on adding in the `Ctrl/Cmd + T` and `Ctrl/Cmd + W` for tabs.
> Add more listeners

- main/main.js
I found out that nodeintegration was enabled. I'm not sure why. Can you test this, and also tell me why?
> Disable nodeIntegration

- src/index.html
- src/preferences.js
Creation of PR.
Starting Commits.
> Show version in settings.

- .github/workflows/auto.yml
- .github/workflows/build.yml
I don't think I'll contribute for any longer. But here's my last one. I realised that you can build for Apple Silicon on Intel, somehow. So I did it.
> Apple silicon

- src/index.html
- src/startup.js
Adding a loading screen to catalyst
> loading screen (1.2)

- README.md
So that the workflow for adding contributors won’t chu- I mean fail.
> Add “Contributors” and remove “Contribeturedssers” or something.

- .pnpm-debug.log
- main/main.js
- pnpm-lock.yaml
- src/index.html
- src/listeners.js
- src/preferences.js
- src/tabs.js
- tailwind.config.js
> New Catalyst 2.0 UI

- src/index.html
- src/lsSaveHandler.js
> Bookmarks Export Feature

- src/firstTime.js
- src/index.html
- src/listeners.js
Welcome to Catalyst bar feature.
> Welcome Bar

- src/search.js
Adds data: to the list of working prefixes.
Untested.
> Data URI support

- src/index.html
- src/pluginCheck.js
- src/pluginWorker.js
I thought this would increase the security of the WIP plug-ins feature a bit.
* Adds function to match plug-in against regexes before adding it to the script, and prints an error into the console if something went wrong
> feat: Add a check to make plug-ins more secure (draft)
